apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: producto-serverless1
spec:
  template:
    spec:
      containers:
        - image: docker.io/lodeonsmm/productos:latest
          ports:
            - containerPort: 8083

