apiVersion: apps/v1
kind: Deployment
metadata:
  name: productos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productos
  template:
    metadata:
      labels:
        app: productos
    spec:
      containers:
        - name: productos
          image: lodeonsmm/productos:v2
          ports:
            - containerPort: 8081
          
