apiVersion: v1
kind: Pod
metadata:
  name: productos
  labels:
    app: productos
spec:
  containers:
    - name: productos
      image: lodeonsmm/productos:v3
      ports:
        - containerPort: 8081
  imagePullSecrets:
  - name: dockerhub-secret
